name: Rust CI

on:
  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta

    - name: Create Cargo LockFile
      run: cargo +beta update

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo +beta build --verbose
    - name: Run tests
      run: cargo +beta test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-libsong_data_core_rust.so
        path: |
          ./target/debug/libsong_data_core_rust.so
        if-no-files-found: error
